name: Python Pipeline

on: 
   workflow_dispatch:

jobs:
  buildABC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          path: .
