name: Python Pipeline

on: pull_request # push

jobs:
  buildABC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          path: .
